### PR TITLE
Added some essential variables

### PR DESCRIPTION
**Pull request by PixyBoi69**
### Like Laravel some more variables should be in Foxdb/Model. i will implement the functionality later or some else can take this as a idea

### CODE REVIEW

**Comment by benkhalife** [comment]
Yes thank you
Now, the methods in the Builder can be used through the model, but some methods and features of the Laravel model are missing.
More features can be added with contributions

**Comment by PixyBoi69** [comment]
Todo:

Make **stdClass** for attributes in Model to set and get it.

**Comment by PixyBoi69** [comment]
I'm not that good with traits so i can't complete HasAttributes on my own

**Comment by parsgit** [comment]
What is the problem ? Please describe the feature you want to add

**Pull request closed without merging**
